[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
diesel = { version = "2.2.8" , features = ["postgres", "chrono"]}
dotenv = "0.15.0"
dotenvy = "0.15.7"
uuid = { version = "1.17.0" , features = ["v4"]}
